package guru.qa.niffler.helpers.api;

import guru.qa.niffler.model.SpendingJson;
import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.Header;
import retrofit2.http.Headers;
import retrofit2.http.POST;



public interface AddSpendApi {
    @Headers("Authorization: Bearer eyJraWQiOiJhZWVjNzNhYy0zOTk4LTQ5OTUtYmZkYS0zZGFlZDA4Zjk4Y2UiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpdmFuIiwiYXVkIjoiY2xpZW50IiwiYXpwIjoiY2xpZW50IiwiYXV0aF90aW1lIjoxNzM0MzU0NDUwLCJpc3MiOiJodHRwOi8vYXV0aC5uaWZmbGVyLmRjOjkwMDAiLCJleHAiOjE3MzQzNTYyNTAsImlhdCI6MTczNDM1NDQ1MCwianRpIjoiZDEzZGMwZWQtZjM0Ny00YjVhLTlhZTMtMWI0ZjBkZTYwYWVkIiwic2lkIjoicVhaYVByWGdJdllrdnZWZVhtOGtfNkgyZi1ZR3dvQkRQTEtZMXJjMGZnOCJ9.eww1VW8Ju4wanx5Rg-iHWTR2i_RMM0Ktn7-yB6FEk7kpjpRc1KfHCQOuQEcuJA3IGaUgllhC7988QP34-tnw9YHZN_T17fBRr6pL9Iv6AoxhJ3f6wcwU-GiXOPAovQA3iVef6MO2ot4yzSZ-Oo7SfnkojBGhPd9waJr_d4OIN904fAKzWMyS44lJyJ0IZRCdASZJQ4SUow-hEJRbMzYi_nsBrbPS5SHXohHvUL0gc4D0Z5gQSQ93EBwGDrIMROxwhmkC6_XkgRT451uIFi1tamFyPUcIOsuf6MNcOxouO0nCVulgJpvISWdMKdS_SXkdAbdVuw0NzxsBsUhtHGSboQ")
    @POST("/api/spends/add")
    Call<SpendingJson> addSpend(@Body SpendingJson json);
}
